export interface NimModel {
  name: string;
  id:   string;
  tag?: string;
}

export type Catalog = Record<string, NimModel[]>;

export const CATALOG: Catalog = {
  '💬 Chat': [
    { name: 'Llama 4 Maverick',     id: 'meta/llama-4-maverick-17b-128e-instruct',            tag: 'Popular' },
    { name: 'Llama 3.3 70B',        id: 'meta/llama-3.3-70b-instruct' },
    { name: 'Llama 3.1 70B',        id: 'meta/llama-3.1-70b-instruct' },
    { name: 'Llama 3.1 8B',         id: 'meta/llama-3.1-8b-instruct',                         tag: 'Fast' },
    { name: 'Llama 3.2 3B',         id: 'meta/llama-3.2-3b-instruct' },
    { name: 'Llama 3.2 1B',         id: 'meta/llama-3.2-1b-instruct' },
    { name: 'Llama 2 70B',          id: 'meta/llama2-70b' },
    { name: 'Mistral Large 3 675B', id: 'mistralai/mistral-large-3-675b-instruct-2512',        tag: 'Powerful' },
    { name: 'Mistral Medium 3',     id: 'mistralai/mistral-medium-3-instruct' },
    { name: 'Mistral Medium 3.5',   id: 'mistralai/mistral-medium-3-5-128b' },
    { name: 'Mistral Small 4 119B', id: 'mistralai/mistral-small-4-119b-2603' },
    { name: 'Mistral 7B',           id: 'mistralai/mistral-7b-instruct-v0.3' },
    { name: 'Magistral Small',      id: 'mistralai/magistral-small-2506' },
    { name: 'Mixtral 8x7B',         id: 'mistralai/mixtral-8x7b-instruct' },
    { name: 'Mixtral 8x22B',        id: 'mistralai/mixtral-8x22b-instruct' },
    { name: 'MiniMax M2.7',         id: 'minimaxai/minimax-m2.7',                             tag: '230B MoE' },
    { name: 'MiniMax M2.5',         id: 'minimaxai/minimax-m2.5' },
    { name: 'GLM 5.1',              id: 'z-ai/glm5.1' },
    { name: 'GLM 4.7',              id: 'z-ai/glm4.7' },
    { name: 'Solar 10.7B',          id: 'upstage/solar-10.7b-instruct' },
    { name: 'Seed OSS 36B',         id: 'bytedance/seed-oss-36b-instruct' },
    { name: 'Sarvam-M',             id: 'sarvamai/sarvam-m',                                  tag: 'Indian' },
    { name: 'Stockmark 100B',       id: 'stockmark/stockmark-2-100b-instruct',                tag: 'Japanese' },
    { name: 'Dracarys 70B',         id: 'abacusai/dracarys-llama-3.1-70b-instruct' },
    { name: 'GPT OSS 20B',          id: 'openai/gpt-oss-20b' },
    { name: 'GPT OSS 120B',         id: 'openai/gpt-oss-120b' },
  ],
  '🧠 Reasoning': [
    { name: 'Kimi K2.6',            id: 'moonshotai/kimi-k2.6',                              tag: '1T MoE' },
    { name: 'Kimi K2 Thinking',     id: 'moonshotai/kimi-k2-thinking' },
    { name: 'Kimi K2 Instruct',     id: 'moonshotai/kimi-k2-instruct' },
    { name: 'DeepSeek V4 Flash',    id: 'deepseek-ai/deepseek-v4-flash',                      tag: 'Fast' },
    { name: 'DeepSeek V4 Pro',      id: 'deepseek-ai/deepseek-v4-pro' },
    { name: 'Step 3.5 Flash',       id: 'stepfun-ai/step-3-5-flash',                         tag: '200B' },
    { name: 'QwQ 32B',              id: 'qwen/qwq-32b' },
    { name: 'Qwen3-next 80B Think', id: 'qwen/qwen3-next-80b-a3b-thinking' },
    { name: 'Qwen3.5 397B',         id: 'qwen/qwen3.5-397b-a17b' },
    { name: 'Phi-4 Mini Reasoning', id: 'microsoft/phi-4-mini-flash-reasoning' },
    { name: 'Nemotron Ultra 253B',  id: 'nvidia/llama-3.1-nemotron-ultra-253b-v1' },
    { name: 'Nemotron Super 120B',  id: 'nvidia/nemotron-3-super-120b-a12b' },
    { name: 'Nemotron Super 49B',   id: 'nvidia/llama-3.3-nemotron-super-49b-v1' },
    { name: 'Nemotron Nano 30B',    id: 'nvidia/nemotron-3-nano-30b-a3b' },
    { name: 'Nemotron Omni 30B',    id: 'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning' },
    { name: 'Nemotron Nano 8B',     id: 'nvidia/llama-3.1-nemotron-nano-8b-v1' },
    { name: 'Nemotron Nano 9B',     id: 'nvidia/nvidia-nemotron-nano-9b-v2' },
    { name: 'Nemotron Mini 4B',     id: 'nvidia/nemotron-mini-4b-instruct' },
  ],
  '💻 Coding': [
    { name: 'Qwen3 Coder 480B',     id: 'qwen/qwen3-coder-480b-a35b-instruct',               tag: 'Best' },
    { name: 'Qwen2.5 Coder 32B',    id: 'qwen/qwen2.5-coder-32b-instruct' },
    { name: 'Qwen3-next 80B',       id: 'qwen/qwen3-next-80b-a3b-instruct' },
    { name: 'Qwen3.5 122B',         id: 'qwen/qwen3-5-122b-a10b' },
    { name: 'Mistral Nemotron',     id: 'mistralai/mistral-nemotron',                        tag: 'Agents' },
    { name: 'Ministral 14B',        id: 'mistralai/ministral-14b-instruct-2512' },
    { name: 'CodeGemma 7B',         id: 'google/codegemma-7b' },
  ],
  '👁️ Vision': [
    { name: 'Kimi K2.5',            id: 'moonshotai/kimi-k2.5',                              tag: 'VLM' },
    { name: 'Llama 3.2 90B Vision', id: 'meta/llama-3.2-90b-vision-instruct' },
    { name: 'Llama 3.2 11B Vision', id: 'meta/llama-3.2-11b-vision-instruct' },
    { name: 'Gemma 4 31B',          id: 'google/gemma-4-31b-it' },
    { name: 'Gemma 3 27B',          id: 'google/gemma-3-27b-it' },
    { name: 'Gemma 3n E4B',         id: 'google/gemma-3n-e4b-it',                            tag: 'Edge' },
    { name: 'Gemma 3n E2B',         id: 'google/gemma-3n-e2b-it',                            tag: 'Edge' },
    { name: 'Phi-4 Multimodal',     id: 'microsoft/phi-4-multimodal-instruct' },
    { name: 'Phi-4 Mini',           id: 'microsoft/phi-4-mini-instruct' },
    { name: 'Nemotron Nano 12B VL', id: 'nvidia/nemotron-nano-12b-v2-vl' },
    { name: 'Llama Guard 4 12B',    id: 'meta/llama-guard-4-12b',                            tag: 'Safety' },
  ],
  '🔬 Science': [
    { name: 'AlphaFold2',           id: 'deepmind/alphafold2' },
    { name: 'AlphaFold2 Multimer',  id: 'deepmind/alphafold2-multimer' },
    { name: 'ESMFold',              id: 'meta/esmfold',                                      tag: 'Protein' },
    { name: 'ESM2 650M',            id: 'meta/esm2-650m' },
    { name: 'Evo2 40B',             id: 'arc/evo2-40b',                                      tag: 'DNA' },
    { name: 'Boltz2',               id: 'mit/boltz2' },
    { name: 'DiffDock',             id: 'mit/diffdock' },
    { name: 'ProteinMPNN',          id: 'ipd/proteinmpnn' },
    { name: 'RFdiffusion',          id: 'ipd/rfdiffusion' },
    { name: 'FourCastNet',          id: 'nvidia/fourcastnet',                                tag: 'Weather' },
    { name: 'CuOpt',                id: 'nvidia/cuOpt',                                      tag: 'Routes' },
  ],
  '🛡️ Safety': [
    { name: 'NemoGuard Content 8B', id: 'nvidia/llama-3.1-nemoguard-8b-content-safety' },
    { name: 'NemoGuard Topic 8B',   id: 'nvidia/llama-3.1-nemoguard-8b-topic-control' },
    { name: 'NemoGuard Jailbreak',  id: 'nvidia/nemoguard-jailbreak-detect' },
    { name: 'GLiNER PII',           id: 'nvidia/gliner-pii',                                 tag: 'PII' },
  ],
};
